### PR TITLE
Conclusion

### PR DESCRIPTION
**Pull request by JThakral20**
Hi team - here's an initial draft of the conclusion. I was trying to think how best to structure this. Please let me know your thoughts.

### CODE REVIEW

**Comment by A-PS1999** [comment]
Hey @JThakral20, I took a look at your draft. Overall I though there was good stuff in there, though I felt that it perhaps repeated some of the things discussed earlier in the report a little too closely.

I've uploaded my attempt at a conclusion, taking some inspiration from yours, to the docs folder also. Please let me know what you think and, if you like, take inspiration from it also for changing your own.

**Comment by JThakral20** [comment]
Hi Sam, thanks for taking a look and writing another version. I see what you mean. To be honest after chatting to some other people on our course - it seemed as if the conclusion should summarise what has already been covered in the report so I ended up amending my draft along those lines. However, I am happy to go with your amended version as I think it goes into more detail in certain areas. I would say maybe it's worth us still having a paragraph about using an agile workflow? I'm not sure we've mentioned it in any detail elsewhere in the report? Let me know your thoughts

**Comment by A-PS1999** [comment]
Yeah I think discussing the Agile workflow would be good. I tried fitting it into mine but it ended up mainly being a small mention at the end. Feel free to create a new conclusion that synthesises both of our drafts and include a little more about Agile if you like.

**Comment by JThakral20** [comment]
Okay thank you Sam - will do!

**Comment by JThakral20** [comment]
Hi team - here's an amended version of the conclusion that combines what @A-PS1999  and I wrote. Please let me know your thoughts.

**Review by A-PS1999 — APPROVED** [review]
Hey @JThakral20, I'm happy for this version to be added to the README so that it can be merged into `main`.

**Pull request merged**
