### PR TITLE
Create the buttons UI and the Main menu background

### PR DESCRIPTION
**Pull request by erer1022**
Hey guys, try to design the main menu interface a little bit. Upload the background and buttons UI.
Screenshot 2024-02-29 at 11 54 53
Currently will be displayed as the attached picture.
I'll try to code some interaction with these buttons later on.

Maybe we can name our game next week? Then I will add the name to the main interface.

And if anyone wants to add more buttons/functions to the main menu interface, please feel free to comment.

### CODE REVIEW

**Review by A-PS1999 — APPROVED** [review]
This looks good to me and I'm happy for it to be merged. Out of curiosity, what's your intention for the combat button?

**Comment by erer1022** [comment]
@A-PS1999 Hi Sam, thank you for your review. 

I want to create a class for the button. I suppose if the user clicks on the button, then it will change state to the combat state? I read your code, if I understand right, the "TITLESCREEN state" is for the main menu right? 
If this is the case, then it will change from "titlescreen_state -- to --> combat_state"

Your code is very clear and understandable, do you have some suggestions for this part?

**Comment by A-PS1999** [comment]
I believe Ricardo had also written some code for buttons in his branch, but it would be great if we could have one definitive and reusable button class, as I also need at least one button in the combat screen. If you could make one and put it in a folder called 'GUI' or 'ui_elements' or something like that, it'd be useful.

I think what we'll need to do, given how Processing works, is to have the mousePressed() and other such input event-catching functions exist somewhere on the top level of the program, but pass in a function from the game engine which will process the input using state-specific logic for the game's current state.

**Comment by erer1022** [comment]
Yes, I think so. And I see there's a good example in the Processing library, 
(it is located at FIle -> Examples -> GUI) and I want to do a similar one. 

For the button, I will create a GUI folder right now, I found some great GUIs last night. :D

**Comment by JThakral20** [comment]
This looks great! Also after talking to Sam about having a shop in the game I started working on having a shop to buy cards etc. So maybe worth adding a button for the shop in the menu?

**Comment by erer1022** [comment]
٩(•̤̀ᵕ•̤́๑)ᵒᵏᵎᵎᵎᵎ   I'll update tonight!

**Comment by A-PS1999** [comment]
Having buttons for the shop and combat on the menu for testing purposes is good, but the actual flow of the game should be as follows:

1. A 'Start' button on the main menu that goes to the map state. It also will probably initialise the Player object.
2. From the map screen, the player can go to one of the starting nodes, which is probably combat.
3. This repeats with new nodes as the player progresses, though besides combat there would also be some nodes for the shop.

**Comment by erer1022** [comment]
Got it.

**Comment by A-PS1999** [comment]
@erer1022 I've merged this branch in with `main`. Is it alright if this branch is deleted now?

**Comment by erer1022** [comment]
Yes, thank you Sam.

**Pull request merged**
