### PR TITLE
Initial version of shop state

### PR DESCRIPTION
**Pull request by JThakral20**
Hey team here’s an initial version of the shop state -> the background of the shop has to be changed + I just need to edit the images on the cards (ignore the white rectangles). I added/edited some stuff in the map state + map loader + the card class + Deck-> please let me know if there’s anything I need to change/fix. I need to add some more nodes on the map for the shop but I just wanted an initial one to check it’s working how it should first.

### CODE REVIEW

**Review by A-PS1999 — CHANGES_REQUESTED** [review]
There are some mistakes here which need correcting, as well as a few areas where I personally think you should choose to take a different approach:

- I think it's a bad idea for the Card class to contain a CardImgLoader class. This would result in every single card loading images, which I imagine would have a bad impact on performance and memory. That's precisely the reason why I chose to have the CardImgLoader be a separate class.
    
    Why did you not take an approach similar to what I did, where I use a CardImgLoader in the place where I need the cards (in my case, the combat encounter) for displaying the cards and therefore not loading them in as often?
- I don't agree with 'buy' being part of the Card class itself, personally. As it stands the shop will only sell cards, so I don't see why you can't just set up some functions in the shop state to handle it given that you have the information you need for the purchase from the card class and player class.
    
    I think cards as a class, besides having an inherent cost value, should solely concern themselves with play in the interest of separation of concerns.
- I don't think you should be throwing exceptions for things which aren't explicitly errors. If a player can't afford a card, that's not an error, that's a potentially expected aspect of play. The use of a boolean would be more appropriate, in my opinion.
- `src/engine/ShopState.pde` appears to basically just be my code and doesn't look appropriate for the shop.
- `src/engine/ShopState/ShopState.pde` looks basically the same. I'm not sure what's up with this.
- I'd suggest removing/cleaning up the several `sketch.properties` files you've created as they're not necessary.
- If you're going to change `CARDTYPE_DEFENCE` to `CARDTYPE_DEFENSE` I do hope you went through and changed all the places I used that as well. Otherwise you're going to break my code. Personally, I think such a minor change is not necessary and is likely to cause more issues than it fixes.

**Comment by JThakral20** [comment]
Whoops sorry for that I think accidentally left the old version of the shop state rather than the updated version I’ve done in the build file. And thanks for the feedback I’ll take a look at the other points you made.

**Comment by RicardoMiles** [comment]
Hi @JThakral20  I found some conflicts in ```MapState.pde```. Thanks for amendment for shop nodes' flow. Could you mind cancelling your changes to ```MapState.pde``` for now, I've saved a copy of your current ```MapState.pde``` on that branch to my local folder and I'll take care of modifying that file. I am scared of changes will make mapscreen broken. I will try to validate soon

**Review by RicardoMiles — CHANGES_REQUESTED** [review]
Hi @JThakral20   I found some conflicts in ```MapState.pde```. Thanks for amendment for shop nodes' flow. Could you mind cancelling your changes to ```MapState.pde``` for now, I've saved a copy of your current ```MapState.pde``` on that branch to my local folder and I'll take care of modifying that file. I am scared of changes will make mapscreen broken. I will try to validate soon

**Comment by RicardoMiles** [comment]
@JThakral20 There are some mistakes here which need correcting, as well as a few areas where I personally think you should choose to take a different approach:

* I don't agree with ```enterNode``` method being part of the CombatNode or ShopNode class itself, personally. You can just set up some functions in the map state to handle click event such as the previous ```goToComvbat()``` method. If you need, I can write it for your use.


* ShopNode could just like the origin CombatNode.pde in build folder in order to test, I would change the .json file map for your test. And I also recomended to code with shop-screen first, which should be changed in ShopState.pde. The screen entrance to shop screen could be fixed by me, and I think it is no need to change the MapState and CombatNode right now. I can p
rovide some method like goToShop() for testing.


* The logic and flow in MapLoader.pde also could be updated by me. Why not let the Node.pde/MapLoader.pde/CombatNode.pde/MapState.pde as it used to be ? I am pretty appreciate your work on inspiring my ideas !!


* Thanks for design of setClickable() method, I am still considering if it could be optimized or simpler to change the bool clickable because of the calculation of actionpoint and distance between nodes. So I prefer put the setClickable() method in updating flow of mapLoader

**Comment by JThakral20** [comment]
Hi @RicardoMiles - sure thing thank you for the feedback I will take a look!

**Comment by JThakral20** [comment]
Hi team - I think the merge conflicts have been resolved now. I've tried to implement the suggestions by @A-PS1999  and @RicardoMiles. Ricardo if possible it might easier if you could set up the functions in the map state to handle click event. I'm happy to follow what you think would be appropriate. I'm not entirely sure what needs to be done with the screen entrance to shop screen so if you could please have a look at that. Furthermore, please could you implement a goToShop() for testing.

**Review by A-PS1999 — CHANGES_REQUESTED** [review]
Hey Jasmine, thanks for the update, but it seems to me that there are still a couple mistakes and lingering bits here.

1. Lines 183-185 and line 291 of `src/combat/CombatEncounter.pde` look like they should be deleted as they appear to be leftovers from the merge conflict.
2. You appear to have deleted `src/entities/Enemy.pde` for some reason. Please restore it.

Otherwise, it looks alright to me.

**Comment by JThakral20** [comment]
Thanks Sam - I will take a look and on second glance there's something I need to fix in the shop node

**Comment by RicardoMiles** [comment]
@JThakral20 I've written the goToShop that goes into the shopstate, but I'm sure this doesn't work yet because I realized that your ShopState doesn't have a constructor method. I've also done the handling of click events, and I've upgraded the display (I've updated the clickable vs. non-clickable visuals)
If it is possible, write a constructor function for your own state like the other states so that other interfaces can call it.
Because there are some new changes to ```MapState``` and ```MapLoader``` recently, we still need to discuss them in the future on merge, I've temporarily moved the ```MapState``` on the ```shop_state``` branch to provide the ```goToShop()``` method, but this will definitely create a conflict in merge, so we'll talk about it when the time comes, let's get the constructor function out of the way first!

**Comment by RicardoMiles** [comment]
By the way , I have no idea with what happened to that on shop_state branch, a little bit comfused
@A-PS1999 
image

**Comment by JThakral20** [comment]
Okay thanks Ricardo will take a look. As for the other issue you've highlighted - the build file does run on processing but for some reason generates a sketch properties file. This changes the main to another file when it should be EntryPoint.ide. When I change it to EntryPoint it runs completely fine. I didn't have this issue at all before so I'm not sure what's causing it as I really don't think I made any changes that would cause it but 100% sure.

**Comment by RicardoMiles** [comment]
@JThakral20 Thanks a lot, Jasmine! No worries, I am just curious. I had never met this issue before either.

**Comment by JThakral20** [comment]
Hi @RicardoMiles - thanks for creating the gotoShop method. Just wanted to clarify a few things. I do have a constructor for the shop state which has an array list of cards. Should the gotoShop method create the array list of cards. Also the enemies are not initialised in the method. Maybe that was causing a problem with the constructor? Let me know what you think.

**Comment by JThakral20** [comment]
Also just wanted to ask should I remove the mapTemp.json file? I saw it's not in the main branch anymore.

**Comment by RicardoMiles** [comment]
Hi Jasmine@JThakral20 , Hope your eyes are feeling better.
I apologize for previously and very accidentally ignoring the constructor you wrote. Please forgive the oversight, it was due to my vscode settings habit of automatically collapsing indented blocks of code.
The constructor method indented an extra tab, would you mind if I adjusted the indentation if I could?
image
I'll change the code related to this I'll let you know when everything is ready as soon as possible!

**Comment by JThakral20** [comment]
Hi @RicardoMiles - thank you so much I appreciate it. And no worries at all - that makes sense! Feel free to adjust the indentation and great thanks.

**Comment by RicardoMiles** [comment]
@JThakral20 By the way, feel free to remove mapTemp.json. And highly recommend that change your local .gitignore to sync with the .gitignore on repo’s main branch

**Comment by JThakral20** [comment]
Okay great - thank you!

**Comment by RicardoMiles** [comment]
Hi team!@A-PS1999 @erer1022 @JThakral20 @Doctor-TOTORO 
I've made and tested changes to the ```goToShop()``` method, and to the ```createNode()``` method in the class ```MapLoader``` section related to the ShopNode, as well as to the ```drawState()``` section of MapState, and the associated mouse&keyboard mapping handle.
ShopNode and ShopState are now available. I also updated a hard mode map ```mapChoiceHard.json``` and applied ```goToShop()``` to the EndState's shopButton on @Doctor-TOTORO Lanai's behalf to implement the logic to return to the store and then back to the map.
I have no idea to deal with conflicts, could you mind helping us,Sam@A-PS1999? I have change the shop_state branch's code up to date with the latest main before I implement shopState feature.

**Comment by A-PS1999** [comment]
> Hi team!@A-PS1999 @erer1022 @JThakral20 @Doctor-TOTORO I've made and tested changes to the `goToShop()` method, and to the `createNode()` method in the class `MapLoader` section related to the ShopNode, as well as to the `drawState()` section of MapState, and the associated mouse&keyboard mapping handle. ShopNode and ShopState are now available. I also updated a hard mode map `mapChoiceHard.json` and applied `goToShop()` to the EndState's shopButton on @Doctor-TOTORO Lanai's behalf to implement the logic to return to the store and then back to the map. I have no idea to deal with conflicts, could you mind helping us,Sam@A-PS1999? I have change the shop_state branch's code up to date with the latest main before I implement shopState feature.

Regarding the merge conflicts, are you sure that `main` was totally up to date before you merged it with the shop state branch? You should be able to resolve the merge conflicts locally.

**Review by RicardoMiles — APPROVED** [review]

**Comment by RicardoMiles** [comment]
Hi Sam@A-PS1999 
Since the merge conflicts was solved and code is tested to be run successfully, could you mind double checking for the change when you are available. No hurries. I am sorry for the late implementation of these features.

**Comment by JThakral20** [comment]
hey just to clarify my last commit was purely to pull Ricardo's changes onto my branch where I just solved a few conflicts I had locally but have deferred all the changes Ricardo made. Hope that's okay.

**Comment by RicardoMiles** [comment]
Hey Sam @A-PS1999
Thanks for your notice. I have now resolved this file merge conflict on .DS_Store file right now.
I apologize for not resolving this in time, as it's a new issue from the process uploading process attached to the process, which as you know, I didn't have yesterday. So .gitignore ignores this Desktop Services Store file of macOS users, but .gitignore does not sync itself. So Jasmine's macBook generated it again and one of us accidentally ignored it somewhere later commit.

**Review by A-PS1999 — APPROVED** [review]
This looks alright, thanks.

**Comment by RicardoMiles** [comment]
Hi Jasmine!@JThakral20 
Given that all the changes on this branch have already been synced to ```hard-mode-implementation```  and ```hard-mode-implementation``` has been merged to the ```main``` branch.
So this pull request doesn't need to exist. 
Also feel free to delete branch ```shop_node```.

**Comment by JThakral20** [comment]
Okay thank you Ricardo! I will delete the shop_state branch now

**Pull request closed without merging**
