### PR TITLE
Combat info popup

### LINKED ISSUE #83: add-combat-tutorial-popup
I'm creating this issue to track the creation of a combat tutorial popup of some kind, as part of resolving the issues raised from user feedback.

### PR DESCRIPTION
**Pull request by A-PS1999**
I added an initial combat help screen with some info on enemy intent icons, text to clarify attacking when there's an active card and icons for a couple status effects which lacked them.

I may go back and see how I can add extra combat-related info at a later stage, but right now I think these changes are good to merge in so we at least have something.

### CODE REVIEW

**Review by RicardoMiles — CHANGES_REQUESTED** [review]
Thanks Sam @A-PS1999 
The info looks great. But help button and tutorial display have some problem
image
image
It would be better if the display area could be fix

**Comment by A-PS1999** [comment]
Hey @RicardoMiles, I tried resizing them. It looks fine for me so it's going to be tough for me to pick values such that it looks alright for you. The only thing that matters is that it looks alright on the lab computer.

**Comment by RicardoMiles** [comment]
Hi Sam@A-PS1999 Yes, you're quite right. We just need fit the lab machines' display. My laptops and desktop are all 1080p resolution, so it's exactly the same as the lab machines' display effect. I totally understand your dilemma. So I'll try to make some adjustments to the display position according to lab machine soon

**Review by RicardoMiles — APPROVED** [review]

**Comment by RicardoMiles** [comment]
Thanks Sam@A-PS1999 It does look better now after resize, both the lab and my laptop! Feel free to merge it to ```main```.

**Pull request merged**
