### PR TITLE
Game balance implemented

### PR DESCRIPTION
**Pull request by RicardoMiles**
Hi team! @A-PS1999 @erer1022 @Doctor-TOTORO @JThakral20 
New game balance has been implemented
*  Change the initial AP deposite as 2, in case users lose in the first turn.
*  Change the sacrifice supplimentary HP as 20, in case the Golem's damage too heavy to recover into value > 0.
*  Consume AP as regular flow 
*  Consume AP according to level gap

### CODE REVIEW

**Review by A-PS1999 — CHANGES_REQUESTED** [review]
Hey @RicardoMiles, thanks, this looks better in terms of AP management and how it works on the map now.

I did come across one issue though. On Hard mode I did one of the first battles and won, giving me a total of 4 AP. I went to a shop node 4 spaces away and then was unable to proceed any further after I left that shop as I had spent all my AP getting to the shop.

I think we need to do something to prevent that possibility from occurring during the game demo on Monday. I'd either make it so that the player gains 1 AP when they leave a shop node (to prevent being totally stuck if they leave) or alternatively make it so they can't enter a shop node if doing so would prevent them from moving any further.

**Comment by RicardoMiles** [comment]
Thanks Sam！ @A-PS1999 
When I tested it, the case covered this condition. I also found this oddity, but I didn't move it because I scared of touching too much code, in fact it would make sense to just add another judgment in the ```ShopState``` to make the ```back``` button in ```ShopState``` delete the ```mapTemp.json``` and go back to the menu when the AP is 0. It makes more sence.
I would read through Jasmine's updated ShopState code and try to make this update as soon as possible.If you approve of the scheme I've just described

**Comment by RicardoMiles** [comment]
Hi Sam@A-PS1999 
Based on your feedback, improvements have been made to the scheme I mentioned
*  Displays a warning when carrying 0 AP into a shop
*  The back button in Shop returns directly to the menu and removes ```mapTemp.json``` when the AP is consumed to exactly 0 .

**Comment by A-PS1999** [comment]
Hey @RicardoMiles, thanks for making that change. Still, I think it would be better if the warning happened before the player enters so they could choose not to enter. Otherwise, the outcome is essentially the same in that the player could enter the shop without realizing that it will make them lose the game.

**Comment by RicardoMiles** [comment]
Hey  Sam@A-PS1999 
If user don't enter shop with one AP but return to the menu, the load button in menu will be on. That will confuse users. And it's not impossible to make a judgment call to show alert message when user got 1 Ap and only one ShopNode to enter. And delete the mapTemp.json in mapState when trigger backbutton . It will make more sense, but that would be reading and writing to the file again, which is too much overhead for the program and would make it slower.
When the player has only one action point, and only the store is accessible, that means he loses. Avoiding him entering the store could not change the case, but I can change the map so that the store isn't in the necessary intersection relay node, and the "1 AP 1 ShopNode available" won't appear again, user could choose to use 1 AP to combat and win more AP to move, do you think that's feasible?

**Comment by A-PS1999** [comment]
> Hey Sam@A-PS1999 If user don't enter shop with one ap but return to the menu, the load button in menu will be on. That will confuse users. And it's not impossible to make a judgment call to delete the map in map when user got 1 Ap and only one shopNode to enter, but that would be reading and writing to the file again, which is too much overhead for the program and would make it slower. When the player has only one action point, and only the store is accessible, that means he loses. Avoiding him entering the store could not change the case, but I can change the map so that the store isn't in the necessary intersection relay node, and the "1 AP 1 ShopNode available" won't appear again, user could choose to use 1 AP to combat and win more AP to move, do you think that's feasible?

At this point I think anything which resolves this issue will do. If one of the people marking our game on Monday experiences losing the game just by entering the shop, I think it will be bad for us.

**Comment by RicardoMiles** [comment]
> > Hey Sam@A-PS1999 If user don't enter shop with one ap but return to the menu, the load button in menu will be on. That will confuse users. And it's not impossible to make a judgment call to delete the map in map when user got 1 Ap and only one shopNode to enter, but that would be reading and writing to the file again, which is too much overhead for the program and would make it slower. When the player has only one action point, and only the store is accessible, that means he loses. Avoiding him entering the store could not change the case, but I can change the map so that the store isn't in the necessary intersection relay node, and the "1 AP 1 ShopNode available" won't appear again, user could choose to use 1 AP to combat and win more AP to move, do you think that's feasible?
> 
> At this point I think anything which resolves this issue will do. If one of the people marking our game on Monday experiences losing the game just by entering the shop, I think it will be bad for us.

Yes, I couldn't agree more, we shouldn't give users that much frustration. Of course I also think we need to maintain our basic mechanics, the player can certainly understand the AP spending and earning mechanics when he sees the tutorial and hears us explaining it, we just need to move the map a bit and give him the opportunity to weigh his options. Just don't push him to the point where he only has a little left and still has to go into the store, I totally got it.

I will change the map soon.

**Comment by RicardoMiles** [comment]
Hey@A-PS1999 Sam
I have updated map to avoid users facing "1 AP have to go Shop and die" case.
Also, could you please sync the changes(https://github.com/UoB-COMSM0110/2024-group-1/pull/98/commits/a1b7e4b21491b9472a0ed39cf5ba654f471d4082) made in the ```src``` folder to the ```build``` folder, I don't dare to move it because I don't know which one is more up-to-date?

**Comment by A-PS1999** [comment]
Oh yeah fair point I'll move the changes I did to `build` too, I forgot to do that.

**Review by A-PS1999 — APPROVED** [review]
OK, I think this can be merged into `main` again now.

**Pull request merged**
