### PR TITLE
Differentiate and doubled easy&hard mode enemies

### PR DESCRIPTION
**Pull request by RicardoMiles**
Hi team @A-PS1999  @JThakral20  @erer1022  @Doctor-TOTORO 
* Differentiate  the enemy case in hardmode and easymode
* Multiple enemies in some combat case rather than single easy enemy

### CODE REVIEW

**Review by A-PS1999 — COMMENTED** [review]
Hey @RicardoMiles, thanks for working on this. 

Unfortunately I think we're going to need to rebalance the enemies again if we do this because I have tried playing through a few times and even Easy mode is hard! I haven't been able to beat the double spiders. I would keep the single spider in the enemy pool on Easy mode at least.

The Golem is also pretty tough on its own so I'm not sure about having it be present alongside a worm or having 2 golems. 2 golems together could theoretically do more damage together in one turn than the boss can.

**Comment by RicardoMiles** [comment]
Thanks@A-PS1999
Thank you so much for doing this again, I know it's a tedious and trivial job and I'm sorry for bothering you with so many changes again. I was thinking about what we discussed yesterday, so attempting to make the enemies appear pairly. 

The final change was just to make it fun to challenge and simply win at the same time, I used boolean to control the difference between easymode and hardmode appearing as a random caseIf you think there are any changes worth making, I'm sure our whole team will trust your decision, and I think it's very appropriate for you to change it straight away!

**Comment by A-PS1999** [comment]
Yeah, I might make a couple other amendments for balance today. I'll need to try out hard mode and see how it is. I have already gone ahead and amended a couple things.

**Review by A-PS1999 — APPROVED** [review]
In the interests of tomorrow's game demo and having made some improvements and tested it a bit, I think it's best we merge this into `main`.

**Pull request merged**
