### PR TITLE
Add some new card templates

### PR DESCRIPTION
**Pull request by erer1022**
Closes #20

### CODE REVIEW

**Review by A-PS1999 — CHANGES_REQUESTED** [review]
Hey @erer1022, for these to actually be used as assets they're going to need to be an image format rather than .psd, which is a PhotoShop file format. The assets should ideally be .png or .jpeg files.

**Comment by erer1022** [comment]
hi @A-PS1999 , this is in case we may want to do some modifications subsequently to those templates, e.g. maybe you want to modify "deal 6 attack" to " deal 2 attack". I can also export those .psd to .png or .jpeg files if you wish.

**Comment by A-PS1999** [comment]
I think if they are in the assets folder, they should be in a state which can be loaded into the game. That means they need to be an image format. The .psd files would be better in a folder called 'res' (short for resources) or something like that.

**Comment by erer1022** [comment]
ok, When I will create a new folder for these templates. Thank you for your suggestions, Sam :D

**Review by A-PS1999 — APPROVED** [review]

**Comment by A-PS1999** [comment]
Hey @erer1022, I have accepted the change here and merged the branch in. The branch can be deleted now if you don't need it anymore, otherwise you can keep using it for other assets.

**Pull request merged**
