### PR TITLE
Added implementation section

### PR DESCRIPTION
**Pull request by A-PS1999**
I've done a tentatively complete version of the implementation section of the report, though there is still space to add a little more.

Please do let me know if you have any comments or feedback which you think would improve this section. I'm happy to make additions and amendments as necessary.

### CODE REVIEW

**Review by JThakral20 — APPROVED** [review]
Thanks this looks good Sam. We could potentially add more detail to the last point about integrating game states.

**Comment by RicardoMiles** [comment]
Hi @A-PS1999 
I think the Button template can also be mentioned in “Game Asset Handling”. In fact, I also utilized the .PSD prototype created by @erer1022  to create icons, and I intend to be responsible for replacing some other icons with inconsistent visual styles soon. This is also to make the UI style consistent more efficiently.|
And I believe that the Implementation challenge could also include a title for the perpetual maintenance of map data. Specifically, this involves implementing the save & load functionality. The design of the .json file makes it very easy to edit new maps, while the BFS algorithm maintains the map, enhancing the maze-like nature of irreversible branches. The self-updating encapsulation of MapState itself ensures smooth transitions when converting to other states, and the map itself does not occupy memory, relying on real-time updates and maintenance from data stored on the hard disk.

**Comment by RicardoMiles** [comment]
Thanks a lot, Sam. It looks perfect even if no change made！

**Comment by A-PS1999** [comment]
> Hi @A-PS1999 I think the Button template can also be mentioned in “Game Asset Handling”. In fact, I also utilized the .PSD prototype created by @erer1022 to create icons, and I intend to be responsible for replacing some other icons with inconsistent visual styles soon. This is also to make the UI style consistent more efficiently.| And I believe that the Implementation challenge could also include a title for the perpetual maintenance of map data. Specifically, this involves implementing the save & load functionality. The design of the .json file makes it very easy to edit new maps, while the BFS algorithm maintains the map, enhancing the maze-like nature of irreversible branches. The self-updating encapsulation of MapState itself ensures smooth transitions when converting to other states, and the map itself does not occupy memory, relying on real-time updates and maintenance from data stored on the hard disk.

I'll make a new branch and submit an update that adds a bit of discussion of the map stuff. The game asset section's already long enough, I think.

**Pull request merged**
