### PR TITLE
Process initial draft

### PR DESCRIPTION
**Pull request by JThakral20**
Hey team – here’s an initial draft of the process section – please provide feedback/additions that should be made. I will add some photos of our WhatsApp group chat, Kanban board and pull requests to accompany this section. I don’t know whether to expand on this section by discussing the Agile methodology. According to the example report we’ve been given – they discuss Agile methodology in the design section? Let me know what you think.

### CODE REVIEW

**Review by A-PS1999 — CHANGES_REQUESTED** [review]
Hey Jasmine, thanks for this. This comment's probably not the best place for this but it's the easiest way for me to do it: I've gone through and amended a few bits, added some Markdown formatting and shortened some bits to make it closer to the 750 words rough word count. Here's the amended version I came up with below:

> # Working as a team
> 
> The team used the Software Engineering labs as well as weekly in-person meetings to check in on our progress as a team. We used these meetings to identify anything we needed to clarify or get help with. We decided as a team what the essential game states that needed to be achieved for a minimum viable product were and what other game states could be completed later on for the final version of the game. On reflection, it would have been useful to organize an in-person meeting just before the Easter holidays to ensure we all had a clear idea of what we should working on each week of the holidays. 
> 
> However, we were still able to communicate this effectively throughout the holidays using WhatsApp and GitHub to ensure we all knew what needed to be achieved. In order to communicate with each other, we set up a WhatsApp group chat where we organized in-person meetings. It was also used to check in with each other to assess our progress as a group. In addition, it was used for suggesting any small tweaks that needed to be made to the project. 
> 
> ## Tools used
> We used GitHub to host and collaborate on the project. Each member used different branches for each feature of the game i.e. using a branch specifically for the menu state. This meant we always had a working version of the game on the main branch. We set up GitHub so that nothing could be merged into `main` without a pull request. This was valuable as it ensured we reviewed each other's code and helped ensure we were all aligned in terms of how we wanted to implement the different features of the game. In addition, using pull requests allowed any merge conflicts to be reviewed and resolved before being pushed to the main branch. 
> 
> We knew that we potentially had a game that would be relatively complex to create due to the multiple game states we needed to implement. Therefore, it was essential to use a Kanban board to keep track of all the different features we wanted to develop and ensure that they could be completed in the given timeframe of the project. As a team, we divided the workload into different features/game states that needed to be completed. We then delegated different game states to each team member. This meant that each team member had a clear idea of what they should be working on. On reflection, perhaps we could have used the Kanban board more effectively by breaking up the tasks into smaller sub-tasks. For example, creating a task for creating a shop state could have been broken up into smaller sub-tasks within this state. This would have given a greater sense of the progress that had been made.
> 
> ## Team roles
> We divided the workload of the game according to the different game states. Sam worked on the overall structure of the game i.e. implementing the game engine and worked on the combat state in terms of both code and related assets. Ricardo created the map state, created a template for the cards and created other assets like buttons. Lanai worked on the end state of the game. Jasmine created the shop state. Zhuoli created the main menu as well as game assets such as the cards.  
> 
> ## Reflection on working together
> 
> Following the project schedule of the unit, we initially concentrated on creating a minimal viable product. One of the challenges we had was getting a minimum viable prototype working. This meant that we were further behind schedule than was ideal, making it challenging to carry out user testing of the game during the software engineering labs. Instead, we resorted to presenting paper prototypes of our game to users. This meant we still received user feedback and a greater understanding of the Think Aloud and Heuristic Evaluation techniques. We were then able to use these tests later on a far more developed version of the game.  
> 
> Perhaps we faced challenges with getting the minimum viable product working due to the fact that we were working on features individually. This made it more difficult to ensure smooth transitioning between the different game states. To resolve this issue, we carried out game-jam sessions, which helped us make effective progress on the game. Having an in-person session meant that we could discuss things we were unsure of so that we were more aligned on how we wanted to transition between different game states.

Maybe you could go with this version or compare it with your own for ideas on how to amend it? It's not too different really.

**Comment by JThakral20** [comment]
Hi @A-PS1999 , thank you very much for your edits. I'm happy to go with the amended version and have made another commit with these changes. I wasn't sure how to retain your markdown formatting but perhaps this is something I can recreate in the readme file on github?

**Comment by A-PS1999** [comment]
> Hi @A-PS1999 , thank you very much for your edits. I'm happy to go with the amended version and have made another commit with these changes. I wasn't sure how to retain your markdown formatting but perhaps this is something I can recreate in the readme file on github?

Hey Jasmine, here's an overview of how you can use Markdown formatting.

https://www.markdownguide.org/cheat-sheet/

As you say, I'd copy the Process section into the README in an appropriate place and add the formatting there. All I added and all you'd really need to add is some heading formatting.

I'd add the README update commit to this branch too and once it's been checked that it looks OK, this can be merged with `main`.

**Comment by JThakral20** [comment]
Perfect, thank you - will do.

**Comment by JThakral20** [comment]
Hi team - I've added the process section to the readme file.

**Review by A-PS1999 — CHANGES_REQUESTED** [review]
Hey Jasmine, the only thing I think could be improved before we merge this is that for some reason your pull request includes some files like `.README.md.swp` and `.process_section.md.swo`. 

If possible could you please remove these?

**Review by A-PS1999 — CHANGES_REQUESTED** [review]
Hey, `.process_section.md.swp` is still in there, which also looks to me like something we don't need.

**Comment by JThakral20** [comment]
Thanks - I've removed the .swp file now - hopefully it's fine now?

**Review by A-PS1999 — APPROVED** [review]
Thanks, that's better.

**Pull request merged**
