### PR TITLE
Update the map screen to fix the OOP paradigm.

### PR DESCRIPTION
**Pull request by RicardoMiles**
Update the map screen basic codes into OOP style in order to interactive with the combat screen and read data from Game engine.

### CODE REVIEW

**Review by A-PS1999 — CHANGES_REQUESTED** [review]
Thanks Ricardo. Here's a list of changes which I think will be required before this can be merged:

-  Remove any `Enemy` and `CombatEncounter` references, so basically remove anything combat related.
- Use the `handleMouseWheel` method instead of `void mouseWheel`
- Use the existing button.pde class or create a sub-class with a different filename to use.
- Consider creating a `CombatNode` subclass to properly initialise an array of enemies which you can pass to the CombatState instance you create when changing state.

**Comment by RicardoMiles** [comment]
Open another pull request as the recommended amendment have been done.

**Comment by A-PS1999** [comment]
You don't need to make a new request. I'll reopen this.

**Review by A-PS1999 — APPROVED** [review]
Thanks Ricardo, this looks fine for now.

**Comment by A-PS1999** [comment]
I've merged the changes in. Please delete the branch if you feel it's no longer needed.

**Comment by RicardoMiles** [comment]
@A-PS1999 
Thanks for approving ！

**Pull request merged**
