### PR TITLE
Visual and audio assets

### LINKED ISSUE #17: Add art assets
Add art assets in order to make demo prototype's UI. Including Music and visual element.

### PR DESCRIPTION
**Pull request by RicardoMiles**
Hi @A-PS1999 @Doctor-TOTORO @JThakral20 @erer1022 
Would you mind reviewing the art assets I've submitted to see if there are any issues? I'd like to merge them into the main branch for everyone to use when creating new branches. I've uploaded the documentation for the template file in specific folder, two cards I've designed, and the template file itself. If there are no objections, may I proceed with merging them into the main branch?

### CODE REVIEW

**Comment by erer1022** [comment]
These two card examples look good to me! Thank you for your design template, Ricardo. We can communicate the details about how to apply it to other cards in today's meeting. I wish I could help you to complete other cards in the reading week!

**Review by A-PS1999 — APPROVED** [review]
Hey Ricardo, thanks for this, these look good. I'd be happy for this to be merged as is, though to improve the organisation of our files I think it would be good if all assets were placed in a dedicated folder named 'assets'. The 'assets' folder could be within images or somewhere else. I'm also happy to support with the creation of some assets, such as of the player character or enemies.

**Comment by erer1022** [comment]
Hi @A-PS1999 , Ricardo has guided me how to designed these cards, and I will follow up the cards' design.
I'm currently replicated the cards according to the cards type from slay the spire
(below is the reference link)
https://slay-the-spire.fandom.com/wiki/Defect_Cards

And I'm intending to create some templates for **attack / skill / power**, with the the rarity in **common / uncommon**.
In case of you may need modify the specific elements on the card, I'll uploaded the .psd then we can modify it whenever we want.

For you convenience, as you're currently working on the battle state, do you want to pick some specific cards from the link, or I just pick some randomly to create the template?

(attached a sample I created today's morning)
Skill_Charge Battery

**Comment by A-PS1999** [comment]
Hey @erer1022, I don't mind really. As long as a few card assets of each type are available to use, I can use them when I get to implementing the battle state UI.

**Pull request merged**
