### PR TITLE
Add some gameplay classes

### PR DESCRIPTION
**Pull request by A-PS1999**
Hey team, in connection with #21 and what we discussed at our last meeting, I've created several important classes, especially Entity and Player.

Please have a look and let me know what you think. If you think any changes should be made please leave a comment saying as much, or otherwise it'd be great if this could be approved so that I can merge it into `main`. Of course, even once merged, it's probable that further changes/additions will be made to these in future.

### CODE REVIEW

**Comment by A-PS1999** [comment]
Note that this pull request connects to issue #21, which I have now closed as it was meant to be connected/part of this one.

**Comment by Doctor-TOTORO** [comment]
I think it's quite great, but if possible, could you add some comments to it, so that it can be more understandable for us to use later?

**Comment by A-PS1999** [comment]
> I think it's quite great, but if possible, could you add some comments to it, so that it can be more understandable for us to use later?

Sure @Doctor-TOTORO , I can add some comments. Is there any particular part you don't understand or think it would be good to have comments for?

**Comment by Doctor-TOTORO** [comment]
Nothing particularly part, perhaps some brief comments could be added after certain functions? Then it would be easier to find when calling back I think.

**Pull request merged**
