### PR TITLE
Hard mode feature implementation

### PR DESCRIPTION
**Pull request by RicardoMiles**
Hi team! @A-PS1999 @Doctor-TOTORO @JThakral20 @erer1022 
*  New feature: Hard mode implemented.
*  Bugfixes: VIsible connection lines would only show in map state.
*  New feature: Add golem to random enemy pool.
*  Optimise : Remove Enter button  in case players are confused
*  Optimise : Redesign the background picture and map tutorial picture assets 
*  Optimise : Redesign the UI part for HP and AP display 
*  New feature: Mouse tracking “where am I” cursor marker are implemented (real-time )

CombatState hasn't been touched except for the addition of a clear screen function to the drawing screen.
I made some optimizations to the game to deal with the feedback.The code is working, no original features or basic functionality is affected.

### CODE REVIEW

**Comment by A-PS1999** [comment]
Hey @RicardoMiles, I'd check this but it looks like you have a merge conflict with `.DS_Store` for some reason, which probably should be resolved first before I review.

**Comment by RicardoMiles** [comment]
Hey Sam @A-PS1999 
Thanks for your notice. I have now resolved this file merge conflict on ```.DS_Store``` file right now.
I apologize for not resolving this in time, as it's a new issue from the process uploading process attached to the process, which as you know, I didn't have yesterday. So .gitignore ignores this Desktop Services Store file of macOS users, but .gitignore does not sync itself. So Jasmine's macBook generated it again and one of us accidentally ignored it somewhere later commit.

**Review by A-PS1999 — CHANGES_REQUESTED** [review]
For some reason `Entities/Enemy.pde` has been deleted in here, so I'd re-add that.

I think the black on `apIcon` and `hpIcon` doesn't fit well on the new map background, it's hard to see.

Those are two things I'd definitely fix, but after that I think this can be merged so that we can move on to other things which need doing.

**Comment by RicardoMiles** [comment]
Yep. I merged ```shop_state``` to it yesterday. So there is also a problem of losing ```Entities/Enemy.pde```, because Jasmine's previous management of src folder on commit [091ab04](https://github.com/UoB-COMSM0110/2024-group-1/pull/76/commits/091ab04a596818876ec2dced234da221f1db6b23) was not fixed.
Thanks you for your feedback @A-PS1999 Sam. And I can change the logo of apIcon and hpIcon easily.

**Comment by JThakral20** [comment]
Apologies I'm not sure what happened there as I did restore it after Sam brought this to my attention last week - not sure how it's been deleted.

**Comment by JThakral20** [comment]
But thank you for restoring it again

**Comment by RicardoMiles** [comment]
Hi Sam@A-PS1999 ! 
Changes have been done.
*  ```Enemy.pde```has been restored.(I did it by hand, I hope it wasn't too rude)
*  ```apIcon``` and ```hpIcon``` are optimized to white
*  Make source code up to date with new feature implemented

image

**Review by A-PS1999 — APPROVED** [review]
Thanks Ricardo, please feel free to merge this.

**Pull request merged**
