### PR TITLE
Create initial endstate

### PR DESCRIPTION
**Pull request by Doctor-TOTORO**
Hi guys, I have created some codes in endstate branch about an initial endstate. Also I have created some GUI about it in the same branch. They can be found in src/endstate, lose_example, win_example and endstate_UI. If you want to see the final UI of the endstate, you can download those .png files from endstate_UI, and try the codes in lose_example and win_example. About the page-changing, I just use a blank white page to show it. Any problems of it plz let me know. Thank u all!!😊😊😊 @A-PS1999 @erer1022 @JThakral20 @RicardoMiles

### CODE REVIEW

**Review by erer1022 — APPROVED** [review]
Looks pretty cool

**Review by A-PS1999 — CHANGES_REQUESTED** [review]
The assets look good! However, this code doesn't follow the Object Oriented Programming approach as I think it ought to, nor does it use the framework I set up.

Part of the problem is, we can't have more than one instance of `mousePressed`, `setup` or `draw`, especially if you don't use classes. This will cause problems later. You should have a function called `handleKeyInput` and `handleMouseInput` in your state class, in order to write state-specific input code which will be passed to the top-level `mousePressed` function. A similar process applies for `draw` and other functions.

**Comment by Doctor-TOTORO** [comment]
@A-PS1999 Ok I will edit it later, thank u😊

**Comment by Doctor-TOTORO** [comment]
I have added a button class in /src/endstate and extened gamestate to it. But I don't change the main structure of the state, just move some functions and hopefully that could be seen better than before.

**Review by A-PS1999 — CHANGES_REQUESTED** [review]
I don't think you understand how Java classes are supposed to work and how the code needs to be structured given the constraints Processing puts us under. Here are some issues I identified in your code:

- No class constructor.
- Attempting to change the size of the window when it's already been set at the program's top level.
- Inappropriate and incorrect attempts to set variables like `totalPoints` or `actionPoints`.

In the final code which gets pushed to `main`, I think you should exclude `lose_example` and `win_example` because they're unnecessary and confusing. In addition, I don't think we need an EndButton class as @erer1022 created a button class already in a separate branch which I've just merged into `main`.

**Comment by Doctor-TOTORO** [comment]
@A-PS1999  Sure I have deleted my enbutton class and tried to use the button class created by @erer1022, but I'm now confused with the third point. If you mean I could just delete those variables and use Player.getActionPts directly?

**Comment by A-PS1999** [comment]
@Doctor-TOTORO I mean that you need to do assignments like that in a constructor, and your use of the capitalised `Player` is inappropriate as it's not a class method, and that's also a void function so assigning it to something is useless.

**Comment by Doctor-TOTORO** [comment]
I'm not quite sure I have done the right things, but maybe like this one?
EndState(Player player) {
    actionPoints = player.getActionPts();
    totalPoints = player.incrementActionPts(winBonus);
    setupState();
  }

**Comment by A-PS1999** [comment]
> I'm not quite sure I have done the right things, but maybe like this one? EndState(Player player) { actionPoints = player.getActionPts(); totalPoints = player.incrementActionPts(winBonus); setupState(); }

Mostly correct, except you can't use `incrementActionPts` to assign something to a variable because it's a `void` function.

**Comment by Doctor-TOTORO** [comment]
So the correct thing is use incrementActionPts after "actionPoints = player.getActionPts();", then use getActionPts() again and assign it to totalPoints?

**Comment by A-PS1999** [comment]
> So the correct thing is use incrementActionPts after "actionPoints = player.getActionPts();", then use getActionPts() again and assign it to totalPoints?

I suppose, if that's what you feel is necessary for your use case. Out of curiosity though, because it's a bit vague from the name `EndState`, is this state meant to apply to both win and loss? If so, the action points shouldn't necessarily be incremented every time, as if the player loses they shouldn't gain action points. It might make more sense for the constructor to take a boolean which indicates win/loss and differentiate the state's behaviour from there.

**Comment by Doctor-TOTORO** [comment]
Oh yes I think that could be better. I have added it into the constructor, and pushed the newest endstate, I hope that can meet the requirement.

**Comment by A-PS1999** [comment]
OK, that looks better. You still need to remove the `size()` function you have in `setupState()` because that will interfere with the `size()` at the program's top level, the `EntryPoint` file.

**Comment by Doctor-TOTORO** [comment]
Ah sorry forgot that one. Now it should be deleted.

**Review by A-PS1999 — APPROVED** [review]
Alright, thanks for the improvements. This looks good to merge into main and build upon. Feel free to merge it yourself.

**Comment by Doctor-TOTORO** [comment]
Thank u Sam!!😊

**Comment by A-PS1999** [comment]
@Doctor-TOTORO, I merged `endstate` with `main`. Feel free to either delete the branch or continue working on it.

**Pull request merged**
